# Generated by Django 4.2.16 on 2024-11-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DNCLInterpreter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='input_d',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
